### ISSUE TITLE
V13 Compatibility

### ISSUE THREAD

**Issue by themockster** [reyzor1991/pf2e-wiki#104]
Hello, 

Great mod! Very essential to our Kingmaker campaign.

It currently does not work with Foundry V13, I know it was just released but was wondering if there's any plan on updating it. 

thanks.

**Comment by reyzor1991** [comment]
What version do you use?

**Comment by reyzor1991** [comment]
<img width="1141" alt="Image" src="https://github.com/user-attachments/assets/0ffd256b-9f1f-46f1-984f-993003a92af5" />

**Comment by reyzor1991** [comment]
kinghelper version should be 0.3.0

**Comment by BoreX865** [comment]
i am freaking stupid. It is version 0.3.0. Sorry. The Number in game was too small to read correctly. It says 0.3.0 in the setup.  But I refreshed with the dropbox link. Still same issue :/

**Comment by reyzor1991** [comment]
Any errors in console?

**Comment by reyzor1991** [comment]
Edit module in main menu

<img width="1171" alt="Image" src="https://github.com/user-attachments/assets/73002edd-3178-494f-8262-d98708b055ab" />

**Comment by reyzor1991** [comment]
Look like issue in compatibility libwrapper & color modules

I will check maybe need to delete color module for now
and use string as settings

**Comment by reyzor1991** [comment]
Should be fixed in 0.3.1

**Comment by BoreX865** [comment]
I updated to 0.3.1 and still dont have the hexploration button on the left side like in v12 of Foundry to display the colored hexes..

**Comment by BoreX865** [comment]
To add to this: Our kingdom shrank to 1 hex with the update to v13: 

![Image](https://github.com/user-attachments/assets/28bdacca-d214-4de6-93b6-6d33c7fd896c)

**Comment by reyzor1991** [comment]
This is another module

https://github.com/BernhardPosselt/pf2e-kingmaker-tools

**Comment by BoreX865** [comment]
oooh right. Then I go make a request there. Still the problem that the colored hexes are still missing :/

**Comment by reyzor1991** [comment]
Is this btn still missed?
any errors in console?

<img width="325" alt="Image" src="https://github.com/user-attachments/assets/6f51c273-7125-408e-984d-f0b169188251" />

**Comment by BoreX865** [comment]
lots of errors but mostly combat utility belt which is another module. 

no button 

![Image](https://github.com/user-attachments/assets/d435de46-0122-435c-9036-8e3798690cf8)

Only thing that might of interest could be this: 

![Image](https://github.com/user-attachments/assets/672f2022-5a1b-4824-a1bc-3b69eaf42a43)

**Comment by reyzor1991** [comment]
Try run only with 1 active module
Maybe some conflicts presents

**Comment by BoreX865** [comment]
unfortunately no button :(

![Image](https://github.com/user-attachments/assets/b3face39-c352-44d1-b313-8111fea94139)

![Image](https://github.com/user-attachments/assets/ad7f34c8-e810-4e69-bac4-562413b25e13)

**Comment by BoreX865** [comment]
Something changed after reactivating all modules and now there is a button. and its highlighting all hexes correctly. Except for the kingdom hexes which used to be red

**Comment by BoreX865** [comment]
My guess would be it has something to do with this setting. 
The first few times when I tried to edit the top settlement color it reloaded and resetted to the default setting. Now I deleted the bottom one and inserted it into the top one and it works as intended, after having a weird null error (see below)
But I do now have a colorful map again. Thanks! :)

![Image](https://github.com/user-attachments/assets/360bfa95-d299-4f00-95e2-913549f1d101)

![Image](https://github.com/user-attachments/assets/36fe9b5d-3058-4e7e-803e-f27eedc0c2cf)

**Comment by BoreX865** [comment]
For information sake: Do you know what module or what kit gave hexploration information. I had a button to click on to see more information about the hexes - like what buildings are on it and so on

**Comment by reyzor1991** [comment]
origin kingmaker module I think

https://foundryvtt.com/packages/pf2e-kingmaker

**Comment by BoreX865** [comment]
Hmm then I have to wait for an update for that one. 

What does "Hex Color - Settlement" and "Hex Color - Settlement" mean in difference? The first and second from bottom? whats the last one for

**Comment by reyzor1991** [comment]
I added fix first is claimed

**Comment by BoreX865** [comment]
Check. 
Works for me. Thanks for the awesome support. :)!

**Comment by reyzor1991** [comment]
@themockster
ping me if error still present

**Comment by themockster** [comment]
Apologies for the late return. 

On my end, I still have no update button

I'm on V13, no modules except  yours and the [Kingdom Building, Camping & Weather](https://foundryvtt.com/packages/pf2e-kingmaker-tools) module. 

![Image](https://github.com/user-attachments/assets/efe737fd-c6d8-4790-bd3c-9d13410b0c48)

![Image](https://github.com/user-attachments/assets/b1a077b2-099e-4288-96d2-41320be9680f)

**Comment by reyzor1991** [comment]
Need to turn on official module, because this module works only with oficial 
Also btn in on token control panel

<img width="290" alt="Image" src="https://github.com/user-attachments/assets/762a71dc-e817-469f-9341-b969bb7d8854" />

**Comment by themockster** [comment]
Well of course with the Kingmaker module it would be better ...

Works now thanks 

![Image](https://github.com/user-attachments/assets/4961e2e7-e3ad-4b17-847d-e716625b4c34)

**Comment by themockster** [comment]
Seems I spoke too fast

The Color button is there, but not the hex one. 
![Image](https://github.com/user-attachments/assets/d9aabba1-9ad7-4562-af4e-1d8d91131ba8)

**Comment by reyzor1991** [comment]
hex btn is part of official module not this one

**Comment by themockster** [comment]
Alright, case closed then. Thanks for your support!
